# Xamarin.iOS
# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- main

pool:
  vmImage: 'macOS-10.15'

steps:
- script: sudo $AGENT_HOMEDIRECTORY/scripts/select-xamarin-sdk.sh 6_12_0
  displayName: 'Select the Xamarin SDK version'
  enabled: true

- script: dotnet tool update --global boots
- script: boots --stable XamariniOS

- task: NuGetToolInstaller@1
  displayName: 'NugetTool install'

- task: UseDotNet@2
  displayName: 'Use .NET Core SDK 5.x'
  inputs:
    version: 5.x
    includePreviewVersions: true

- task: NuGetCommand@2
  displayName: 'NuGet restore'
  inputs:
    restoreSolution: '**/*.sln'

- task: Bash@3
  displayName: 'Run script in build-ios.sh file'
  inputs:
    filePath: '**/build-ios.sh'
    arguments: '"net5/net5.iOS/net5.iOS.csproj" "Debug" "iPhoneSimulator"'