# Xamarin.iOS
# Build a Xamarin.iOS project.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xamarin

trigger:
- main

pool:
  vmImage: 'macOS-10.15'

steps:
- task: UseDotNet@2
  displayName: 'Use .NET Core sdk 5.0.400'
  inputs:
    packageType: 'sdk'
    version: '5.0.400'
    includePreviewVersions: true

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: build
    projects: '**/net5.csproj'

